# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb', 'deploy.sh', 'temas', 'new']
markdown: rdiscount

# configuration required for some pages

domain: www.javaperformance.com.br
title: Performance Java
author: Jonas Abreu
email: jonas@vidageek.net

# configuration for ehancements, uncomment to enable

feedburner:
  id: PerformanceJava

google_analytics:
  account: UA-1508082-7

# github:
#   username: ghusername

disqus:
  id: performancejava
