#! /bin/bash

DATE=`date +%Y-%m-%d`

let "NUM=`ls $DATE* 2>/dev/null | wc -l` + 1"

POST=$DATE-$NUM-$1.markdown

echo "---" > $POST
echo "layout: post" >> $POST
echo "title:" >> $POST
echo "permalink:" >> $POST
echo "category:" >> $POST
echo "---" >> $POST

